version: "3.6"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.38
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    volumes:
    - "./configurations/jaeger-ui.json:/etc/jaeger-jaeger-ui.json"
    command: --query.ui-config /etc/jaeger-jaeger-ui.json
    ports:
    - "14250:14250"
    - "14268:14268"
    - "14269:14269"
    - "16686:16686"
  quote:
    build: .
    ports:
      - "65080:65080"
    environment:
      FEATURETOGGLE_SERVER: "http://featuretoggle:8080"
  featuretoggle:
    image: flipt/flipt:latest
    ports:
      - "64080:8080"
    volumes:
      - "./flipt:/var/opt/flipt"
    environment:
      FLIPT_TRACING_JAEGER_ENABLED: true
      FLIPT_TRACING_JAEGER_HOST: jaeger
      FLIPT_LOG_LEVEL: debug

