version: "3.6"
services:
  quote:
    build: .
    ports:
      - "65080:65080"
    environment:
      FEATURETOGGLE_SERVER: "http://featuretoggle:8080"
  featuretoggle:
    image: flipt/flipt:latest
    ports:
      - "64080:8080"
    volumes:
      - "./flipt:/var/opt/flipt"
  jaeger:
    image: jaegertracing/all-in-one:1.38
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      METRICS_STORAGE_TYPE: prometheus
      PROMETHEUS_SERVER_URL: http://prometheus:9090
    volumes:
    - "./configurations/jaeger-ui.json:/etc/jaeger-jaeger-ui.json"
    command: --query.ui-config /etc/jaeger-jaeger-ui.json
    ports:
    - "14250:14250"
    - "14268:14268"
    - "14269:14269"
    - "16686:16686"
  prometheus:
    image: prom/prometheus
    ports:
    - "9090:9090"
