apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: quote-{{ .Values.liveService | replace "." "-" }}
  name: quote-{{ .Values.liveService | replace "." "-" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-{{ .Values.liveService | replace "." "-" }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quote-{{ .Values.liveService | replace "." "-" }}
    spec:
      containers:
      - image: {{ .Values.dockerAccount }}/lecture-quote:{{ .Values.liveService }}
        name: quote
        ports:
        - containerPort: 65080
        env:
          - name: ENV_COLOR
            value: BLUE
        resources: {}
status: {}
