apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: live-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quote-service-{{ .Values.liveService | replace "." "-" }}
            port:
              number: 65080