apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: quote-service-{{ .Values.idleService | replace "." "-" }}
  name: quote-service-{{ .Values.idleService | replace "." "-" }}
spec:
  ports:
  - port: 65080
    protocol: TCP
    targetPort: 65080
  selector:
    app: quote-service-{{ .Values.idleService | replace "." "-" }}
status:
  loadBalancer: {}
