apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - image:  jaegertracing/all-in-one:1.37
        name: jaeger
        ports:
        - containerPort: 14250
        - containerPort: 14268
        - containerPort: 16686
        env:
          - name: COLLECTOR_OTLP_ENABLED
            value: "true"
        resources: {}
status: {}
