apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: quote-green
  name: quote-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quote-green
    spec:
      containers:
      - image:  k830206/lecture-quote:latest
        name: quote
        ports:
        - containerPort: 65080
        env:
          - name: ENV_COLOR
            value: GREEN
        resources: {}
status: {}
