apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jaeger-service
  name: jaeger
spec:
  ports:
  - name: frontend
    port: 16686
    protocol: TCP
    targetPort: 16686
  selector:
    app: jaeger
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jaeger-internal-service
  name: jaeger-internal
spec:
  ports:
  - name: collector
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: thrift
    port: 14268
    protocol: TCP
    targetPort: 14268
  selector:
    app: jaeger
  type: NodePort
status:
  loadBalancer: {}
